### ISSUE TITLE
Backup 1.19 バックアップ先の参照

### ISSUE THREAD

**Issue by k9ta** [JunSotaSoftware/Backup#18]
Backup v1.19 を愛用させていただいております。ありがとうございます。
あれっ？と思う程度ですが、間違い探し的なエラーを見つけたのでご連絡いたします。
以下のように進んでください。
トップ画面 > バックアップパターン > 新規作成 > パターン作成 > バックアップ先 > バックアップ先フォルダの追加 > フォルダの指定 > ・・・　フォルダーの参照
バックアップ先を指定しようとしているのに、バックアップ元という表示は変だな・・と。
以上です。よろしくお願いします
![スクリーンショット 2022-08-29 140415](https://user-images.githubusercontent.com/63991036/187128646-4ab57ee8-8552-4e30-ae26-85f30b773787.png)
。

**Comment by JunSota** [comment]
ご報告ありがとうございます。
バージョン1.20bにて修正いたしました。
