### ISSUE TITLE
Backup 1.20bがWindows11セキュリティで隔離されてしまいました。

### ISSUE THREAD

**Issue by hiroswingby** [JunSotaSoftware/Backup#19]
お世話になります。

http://www2.biglobe.ne.jp/~sota/backup.html から最新版（インストーラ付）のBackupソフトウェアをダウンロードしWindows 11上で何度か問題なく使用できていましたが、昨日起動したところWindowsセキュリティによっていきなり隔離されてしまいました。「保護の履歴」を見ると「 Trojan:Win32/Wacatac.B!ml 」を検出したため検疫したとのことです。Microsoft Defender Antivirus の誤検知かもしれませんが、何か情報があれば教えて頂きたくお願いします。

![Backup感染](https://user-images.githubusercontent.com/78009819/208806924-557fc363-453a-4246-9397-fd32acc7c63a.png)

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fWacatac.B!ml&threatid=2147735505

**Comment by JunSota** [comment]
お世話になります。
確認を行うために、まず当方のWindows 11をWindowsセキュリティ（バージョン 1.381.801.0）を使い、フルスキャンでチェックしましたが、脅威は検出されませんでした。また、念のためMalwarebytesのAdwCleaner 8.4.0を使い、Windowsをチェックしましたが、脅威は見つかりませんでした。

次に私のウエブサイトからBackupのインストーラ付きをダウンロード、インストールし、WindowsセキュリティでBackup.exeをスキャンしましたが、脅威は検出されませんでした。

Backup.exeをVirusTotalでチェックしたところ、Microsoft以外のいくつかのウイルス検索ソフトで脅威が検出されましたが、主要なウイルス検索ソフトでは脅威無しと判断されており、誤検出の可能性があると考えております。

おそらくWindowsセキュリティの誤検出と思われます。Windowsアップデートを使って、最新の定義更新プログラムをダウンロードしてみてください。

以上よろしくお願いします。

**Comment by hiroswingby** [comment]
早速のご確認ありがとうございます。

Windows Update を実行した後、保護の履歴の操作から隔離されたファイルを復元しましたが、即座に同じ脅威を検出され隔離されてしまいました。この分野の専門ではないのですが、静的なファイルスキャン時ではなく実行時に問題が検出されている様にも思えます。

![Backup隔離](https://user-images.githubusercontent.com/78009819/209045976-3f97ffe2-3d66-4e64-bb44-400c3f76fc4b.png)

ちなみにWindowsセキュリティのバージョン番号の確認方法をご教授頂けますか、念のため確認しお知らせします。

宜しくお願い致します。

**Comment by JunSota** [comment]
Windowsセキュリティのバージョンは、以下の手順で確認できます。
以下のスクリーンショットは、私のWindows 11の2022年12月22日16時35分のものです。
定義ファイルは最新に更新してあります。
![画像2](https://user-images.githubusercontent.com/44973623/209081949-29d0d035-e04e-4de7-920f-9b084202e46f.png)
![画像3](https://user-images.githubusercontent.com/44973623/209082020-c9db66dd-a334-4c0e-9bcf-8759b995c399.png)
![画像4](https://user-images.githubusercontent.com/44973623/209082045-39a1e925-5058-486c-9895-d5f5cfef941a.png)

**Comment by JunSota** [comment]
マイクロソフトにバージョン1.20bのBackup.exeを送りましたが、脅威の検出が再現できないと返ってきました。

プログラムをコンパイルする時のWindows SDKのバージョンを変更したところ、VirusTotalでの検出数が大幅に減ったので、私のウエブサイトでバージョン1.20cを公開しました。こちらを試してみてください。

![画像1](https://user-images.githubusercontent.com/44973623/209142109-fe712b37-e4d6-45d3-a020-6787870aff22.png)

**Comment by hiroswingby** [comment]
早速 1.20cをインストールし試してみました。結果は問題なく動作しました。私の環境のWindowsセキュリティのバージョンを確認しましたので添付します。当方のバージョン(1.381.913.0)が少し新しい様です。

![Windowsセキュリティバージョン](https://user-images.githubusercontent.com/78009819/209260049-85a4c57c-9369-4145-9423-bcd1b1ec0b17.png)

1.20bもインストール当初は動作していましたので、Windowsセキュリティが自動更新されたタイミングで誤検知されるようになったのだと思います。

お手数をお掛けしました、有難うございました。
