### ISSUE TITLE
設定を保存するタイミングについて

### ISSUE THREAD

**Issue by jarupxx** [JunSotaSoftware/Backup#22]
設定を保存するタイミングについて
アプリ終了時に保存するようですが、パターン設定をしてOK押したタイミングで保存を提案させてください。
よろしくお願いします。

**Comment by JunSota** [comment]
個人的には、現状のアプリ終了時に保存する方法で不都合はないのですが、この方法で不都合がありますでしょうか？

**Comment by jarupxx** [comment]
常駐させて長期間使用していたところアプリとは関係なくOSが落ちて設定が巻き戻ったことがあります。時間をかけて設定したのでショックが大きかったです。

**Comment by JunSota** [comment]
アプリ終了時に呼び出している設定保存の処理を、設定画面を閉じたタイミングでも呼び出すだけで実現できそうですので、実装を検討します。

**Comment by JunSota** [comment]
バージョン1.22で対応しました。

**Comment by jarupxx** [comment]
対応いただきありがとうございました。
